// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionStatus } from "./CollectionStatus";
import type { Game } from "./Game";
import type { Method } from "./Method";

export type CollectionEntry = { id: string, pokemon_id: number, form_id: number, status: CollectionStatus, is_shiny: boolean, encounter_count: number, has_shiny_charm: boolean, sandwich_active: boolean, outbreak_active: boolean, chain_count: number, game_caught: Game | null, method_used: Method | null, caught_at: string | null, notes: string | null, updated_at: string, synced_at: string | null, };
