// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mega Evolution / Gigantamax — cosmetic battle forms, not distinct dex
 * entries (Mega reverts after battle; Gmax doesn't change shininess), so
 * these never get their own `shiny_methods` rows. `kind` is stringly-typed
 * (not an enum) since it's purely display, with a tiny fixed set ("mega",
 * "mega_x", "mega_y", "gmax") that nothing filters/queries on the way
 * Game/Method do.
 */
export type CosmeticForm = { id: number, pokemon_id: number, form_id: number, kind: string, display_name: string, sprite_url: string, shiny_sprite_url: string, 
/**
 * PokéAPI item slug, e.g. "venusaurite" — None for Gigantamax (no held item).
 */
mega_stone_item: string | null, };
