// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every sprite-bearing alternate appearance that isn't a distinct dex
 * entry — battle-only/contextual forms confirmed to revert the instant you
 * leave their triggering context (Mega Evolution, Gigantamax, Zen Mode,
 * Primal Reversion, Blade Aegislash, Busted Mimikyu, Minior's Core
 * colors, ...) AND (since the exhaustive sprite-coverage pass) purely
 * decorative variants with no mechanical difference at all from their
 * parent row (Unown's letters, Vivillon/Alcremie/Furfrou's patterns,
 * Arceus/Silvally's Plate/Memory types, Shellos/Gastrodon's East Sea,
 * ...). Not distinct dex entries either way (none of these change
 * shininess or persist in storage as their own individual), so they never
 * get their own `shiny_methods` rows. `kind` is stringly-typed (not an
 * enum) since it's purely display, with a wide and growing set of values
 * (one per distinct cosmetic transformation/sprite — "mega", "mega_x",
 * "mega_y", "gmax", "zen", "primal", "busted", "east", "fire", "b", ...)
 * that nothing filters/queries on the way Game/Method do.
 */
export type CosmeticForm = { id: number, pokemon_id: number, form_id: number, kind: string, display_name: string, sprite_url: string, shiny_sprite_url: string, 
/**
 * PokéAPI item slug, e.g. "venusaurite" — None for Gigantamax (no held item).
 */
mega_stone_item: string | null, 
/**
 * JSON-encoded array of type names — Mega/Gmax forms can differ from the base form (e.g. Mega Charizard X is Fire/Dragon, not Fire/Flying).
 */
types: string, height: number, weight: number, 
/**
 * JSON-encoded array of ability names — Mega forms typically have a single fixed ability, overriding the base form's normal/hidden ability slots.
 */
abilities: string, stat_hp: number, stat_attack: number, stat_defense: number, stat_special_attack: number, stat_special_defense: number, stat_speed: number, stat_total: number, base_experience: number, ev_yield_hp: number, ev_yield_attack: number, ev_yield_defense: number, ev_yield_special_attack: number, ev_yield_special_defense: number, ev_yield_speed: number, };
