// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CosmeticForm } from "./CosmeticForm";
import type { EvolutionChainEdge } from "./EvolutionChainEdge";
import type { EvolutionChainMember } from "./EvolutionChainMember";

/**
 * Everything the evolution-line chip row needs for one chain: every member
 * (with its stage), every real edge between members, and every member's OWN
 * cosmetic_forms rows (not just the currently-viewed species') — without
 * this last one, a lane's chip icon can only ever show the sprite of
 * whichever single species' page happens to be open (e.g. viewing the
 * chain from Wormadam's own page has no way to know Burmy's Sandy/Trash
 * cloak sprites, since those rows are keyed by Burmy's pokemon_id, not
 * Wormadam's) — returned together since the frontend always needs all
 * three to render correctly regardless of which member's page is open.
 */
export type EvolutionChainData = { members: Array<EvolutionChainMember>, edges: Array<EvolutionChainEdge>, cosmetic_forms: Array<CosmeticForm>, };
