// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pokemon } from "./Pokemon";

/**
 * One member of an evolution-line family, alongside its `stage` — the
 * frontend's chip-row UI groups members by stage so two parallel same-depth
 * paths (e.g. Alolan Rattata/Raticate) or a branch (e.g. Vileplume/
 * Bellossom both reached from Gloom) render as visually distinct clusters
 * instead of one flat, misleadingly linear-looking row.
 */
export type EvolutionChainMember = { pokemon: Pokemon, stage: number, };
