// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvolutionChainEdge } from "./EvolutionChainEdge";
import type { EvolutionChainMember } from "./EvolutionChainMember";

/**
 * Everything the evolution-line chip row needs for one chain: every member
 * (with its stage) plus every real edge between members — returned
 * together since the frontend always needs both to render correctly.
 */
export type EvolutionChainData = { members: Array<EvolutionChainMember>, edges: Array<EvolutionChainEdge>, };
