// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Game = "gen1_vc" | "gen2_vc" | "gen3_rs" | "gen3_e" | "gen3_frlg" | "gen4_dp" | "gen4_pt" | "gen4_hgss" | "gen5_bw" | "gen5_b2_w2" | "gen6_xy" | "gen6_oras" | "gen7_sm" | "gen7_usum" | "lgpe" | "swsh" | "bdsp" | "pla" | "sv" | "go";
