// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audited against Bulbapedia's full `Pokémon games` index (120+ titles) for every
 * game — core or side — with a real mechanism to put a PID-bearing Pokémon into a
 * game that eventually reaches HOME, not just battle with borrowed/virtual ones.
 * Deliberately excluded, with reasons checked rather than assumed:
 * - **Pokémon Champions** — recruited Pokémon can't be deposited to HOME; a
 *   one-way borrow-and-return loop with no shiny-acquisition mechanic of its own
 *   (same reasoning that already excludes Pal-Park-style pure transfers).
 * - **Pokémon Pinball: Ruby & Sapphire** — confirmed via direct research to have
 *   no transfer feature at all, despite a common assumption otherwise.
 * - **PokéPark Wii / PokéPark 2** — no evidence found of any Pokémon-transfer mechanism.
 * - **Pokémon Stadium / Stadium 2, Pokémon Box, Pokémon Bank, Pokémon HOME itself**
 *   — relay/storage/battle-simulator infrastructure that moves existing Pokémon,
 *   not a catching mechanic that creates new ones.
 * - The entire TCG/puzzle/rhythm/photography/edutainment catalog (Trading Card Game,
 *   Puzzle League, Trozei, Shuffle, Pokkén, Detective Pikachu, Snap, Conquest,
 *   Mystery Dungeon, Rumble, Duel, Magikarp Jump, Quest, and the rest of Bulbapedia's
 *   ~80-title minigame/spinoff long tail) — none create a real Pokémon instance.
 * - **Pokémon Winds and Waves** — real, confirmed via independent official Nintendo
 *   sources, but announced for 2027 — hasn't released, so there's nothing to scrape
 *   yet; a known near-future addition, not modeled speculatively.
 */
export type Game = "gen1_vc" | "gen2_vc" | "gen3_rs" | "gen3_e" | "gen3_frlg" | "colosseum" | "xd" | "gen4_dp" | "gen4_pt" | "gen4_hgss" | "ranger" | "ranger_soa" | "dream_world" | "dream_radar" | "ranger_gs" | "gen5_bw" | "gen5_b2_w2" | "gen6_xy" | "gen6_oras" | "gen7_sm" | "gen7_usum" | "lgpe" | "swsh" | "bdsp" | "pla" | "sv" | "legends_za" | "go";
