// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Method = "wild" | "soft_reset" | "breeding" | "masuda" | "chain_radar" | "chain_fishing" | "sos" | "horde" | "dex_nav" | "dex_research" | "outbreak" | "dynamax_adventure" | "catch_combo" | "wormhole" | "event" | "go_wild" | "go_community_day" | "friend_safari" | "brilliant_pokemon";
