// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * If you add a variant here that represents a *repeatable wild-encounter*
 * chaining mechanic (in the spirit of Pokéradar/chain fishing/DexNav/SOS/
 * Catch Combo/Mass Outbreak/Brilliant Pokémon), also add it to
 * `tools/seed-gen/src/deriveShinyMethods.ts`'s `WILD_ONLY_METHODS` Set —
 * nothing in Rust or TS enforces these two lists staying in sync, so a new
 * wild-only method added here would otherwise silently apply to gift/
 * static/trade-only species too (the exact bug class `WILD_ONLY_METHODS`
 * exists to prevent).
 */
export type Method = "wild" | "soft_reset" | "breeding" | "masuda" | "chain_radar" | "chain_fishing" | "sos" | "horde" | "dex_nav" | "dex_research" | "outbreak" | "dynamax_adventure" | "catch_combo" | "wormhole" | "event" | "go_wild" | "go_community_day" | "friend_safari" | "brilliant_pokemon";
