// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PokedexFilters = { search: string | null, generation: number | null, legendary_or_mythical_only: boolean | null, };
