// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pokemon = { id: number, name: string, display_name: string, form_id: number, form_name: string | null, generation: number, sprite_url: string, shiny_sprite_url: string, 
/**
 * Gender-difference sprites — None for the ~90% of species with no visual gender difference.
 */
sprite_url_female: string | null, shiny_sprite_url_female: string | null, 
/**
 * sprite_url's own non-transparent content region, as fractions (0..1)
 * of its canvas — see cosmetic_forms' CosmeticForm.sprite_crop_x doc
 * comment for the full reasoning. Almost always a near-no-op here
 * (sprite_url usually resolves to tightly-cropped official artwork),
 * computed unconditionally anyway so any future species/variety that
 * ever lacks official-artwork/home sprites gets the same fix
 * automatically. Also applies to shiny_sprite_url (a shiny sprite is a
 * pure palette recolor sharing the same alpha shape, confirmed live).
 */
sprite_crop_x: number, sprite_crop_y: number, sprite_crop_width: number, sprite_crop_height: number, 
/**
 * Same idea, measured separately from sprite_url_female (a genuinely
 * different sprite when has_gender_differences is true, not just a
 * recolor) — full-canvas defaults when there's no gender-difference
 * sprite to crop at all.
 */
sprite_crop_x_female: number, sprite_crop_y_female: number, sprite_crop_width_female: number, sprite_crop_height_female: number, 
/**
 * JSON-encoded array of type names, e.g. `["grass","poison"]`
 */
types: string, 
/**
 * -1 = genderless, 0 = always male, 8 = always female
 */
gender_rate: number, is_mythical: boolean, is_legendary: boolean, is_baby: boolean, is_final_evolution: boolean, color: string, shape: string | null, growth_rate: string, 
/**
 * JSON-encoded array of egg group names, e.g. `["monster","plant"]`
 */
egg_groups: string, capture_rate: number, base_happiness: number, height: number, weight: number, 
/**
 * JSON-encoded array of ability names
 */
abilities: string, 
/**
 * Base stats at level 100 — max neutral IVs (31), 0 EVs, neutral nature.
 * Not raw PokéAPI base_stat values.
 */
stat_hp: number, stat_attack: number, stat_defense: number, stat_special_attack: number, stat_special_defense: number, stat_speed: number, stat_total: number, base_experience: number, ev_yield_hp: number, ev_yield_attack: number, ev_yield_defense: number, ev_yield_special_attack: number, ev_yield_special_defense: number, ev_yield_speed: number, has_mega_evolution: boolean, has_gigantamax: boolean, has_gender_differences: boolean, 
/**
 * Steps to hatch from an egg (PokéAPI's raw hatch_counter in cycles * 255).
 */
hatch_steps: number, 
/**
 * Latest English Pokédex description PokéAPI has indexed — None only if no English entry exists at all.
 */
flavor_text: string | null, };
