// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pokemon = { id: number, name: string, display_name: string, form_id: number, form_name: string | null, generation: number, sprite_url: string, shiny_sprite_url: string, 
/**
 * JSON-encoded array of type names, e.g. `["grass","poison"]`
 */
types: string, 
/**
 * -1 = genderless, 0 = always male, 8 = always female
 */
gender_rate: number, is_mythical: boolean, is_legendary: boolean, };
