// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { Method } from "./Method";

export type ShinyMethod = { id: number, pokemon_id: number, form_id: number, game: Game, method: Method, odds_base: number, odds_charm: number, odds_optimized: number, 
/**
 * JSON-encoded array of boost requirement strings
 */
boost_requirements: string, is_best_method: boolean, requires_transfer: boolean, transfer_chain: string | null, citation_url: string, notes: string | null, };
