// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncMode } from "./SyncMode";

export type SyncStatus = { last_synced_at: string | null, is_online: boolean, mode: SyncMode, };
