CREATE TABLE pokemon (
    id                       INTEGER NOT NULL,
    name                     TEXT    NOT NULL,
    display_name             TEXT    NOT NULL,
    form_id                  INTEGER NOT NULL DEFAULT 0,
    form_name                TEXT,
    generation               INTEGER NOT NULL,
    sprite_url               TEXT    NOT NULL,
    shiny_sprite_url         TEXT    NOT NULL,
    sprite_url_female        TEXT,
    shiny_sprite_url_female  TEXT,
    types                    TEXT    NOT NULL,
    gender_rate              INTEGER NOT NULL,
    is_mythical              INTEGER NOT NULL DEFAULT 0,
    is_legendary             INTEGER NOT NULL DEFAULT 0,
    is_baby                  INTEGER NOT NULL DEFAULT 0,
    is_final_evolution       INTEGER NOT NULL DEFAULT 0,
    color                    TEXT    NOT NULL,
    shape                    TEXT,
    growth_rate              TEXT    NOT NULL,
    egg_groups               TEXT    NOT NULL,
    capture_rate             INTEGER NOT NULL,
    base_happiness           INTEGER NOT NULL,
    height                   INTEGER NOT NULL,
    weight                   INTEGER NOT NULL,
    abilities                TEXT    NOT NULL,
    stat_hp                  INTEGER NOT NULL,
    stat_attack               INTEGER NOT NULL,
    stat_defense             INTEGER NOT NULL,
    stat_special_attack       INTEGER NOT NULL,
    stat_special_defense      INTEGER NOT NULL,
    stat_speed                INTEGER NOT NULL,
    stat_total                INTEGER NOT NULL,
    base_experience           INTEGER NOT NULL,
    ev_yield_hp               INTEGER NOT NULL,
    ev_yield_attack           INTEGER NOT NULL,
    ev_yield_defense          INTEGER NOT NULL,
    ev_yield_special_attack   INTEGER NOT NULL,
    ev_yield_special_defense  INTEGER NOT NULL,
    ev_yield_speed            INTEGER NOT NULL,
    PRIMARY KEY (id, form_id)
);

CREATE INDEX idx_pokemon_generation ON pokemon(generation);
CREATE INDEX idx_pokemon_name ON pokemon(name);
